name: Test

on:
  push:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      - name: Install Go
        uses: actions/setup-go@v5.5.0
        with:
          go-version-file: "go.mod"
      - name: Test
        run: go test -cover ./...
